post_install() {
  echo ""
  echo "Setup Tutorial"
  echo ""
  echo "For Flatpak Libadwaita applications, you need to override their permissions:"
  echo "sudo flatpak override --filesystem=xdg-config/gtk-4.0"
  echo ""
  echo "For Flatpak applications, you need to override their permissions:"
  echo "sudo flatpak override --filesystem=xdg-config/gtk-3.0"
  echo ""
}

post_upgrade() {
   post_install
}
